M48
; DRILL file {KiCad 7.0.7} date 2023 September 07, Thursday 11:23:36
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-07T11:23:36-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X54.29Y-140.47
X99.82Y-179.77
X147.46Y-36.34
T2
X53.57Y-35.945
X53.57Y-93.945
X76.57Y-35.945
X76.57Y-93.945
T0
M30
